import Head from 'next/head'
import { Container, Heading } from '@chakra-ui/react'
import MyFooter from '../components/MyFooter'
import MyHeader from '../components/MyHeader'

export default function About() {
  return (
    <Container maxW='75%' p={4}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MyHeader/>
        <Heading mt={8} as='h1' size='xl' noOfLines={1}>
            About
        </Heading>
      </main>

      <MyFooter/>
    
    </Container>
  )
}
