import Head from 'next/head'
import { Container, Heading, Box } from '@chakra-ui/react'
import MyFooter from '../components/MyFooter'
import MyHeader from '../components/MyHeader'

export default function Contact() {
  return (
    <Container maxW={{sm: 'full', xl: '60%'}} p={4} mt={8}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MyHeader/>
        <Box maxW="full" my={8}><img src="t1.jpg"/></Box>
        <Heading mt={8} as='h1' size='xl' noOfLines={1}>
            Contact
        </Heading>
      </main>

      <MyFooter/>
    
    </Container>
  )
}
