import Head from 'next/head'
import { Container, Heading, Box } from '@chakra-ui/react'
import MyFooter from '../components/MyFooter'
import MyHeader from '../components/MyHeader'
import HomeCta from '../components/Home/HomeCta'

export default function Home() {
  return (
    <Container maxW={{sm: 'full', xl: '60%'}} p={4}  mt={8}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MyHeader/>
        <HomeCta/>
      </main>

      <MyFooter/>
    
    </Container>
  )
}
